[package]
name = "combi"
version = "0.1.0"
edition = "2021"

[[example]]
name = "json"
path = "examples/json.rs"

[[example]]
name = "regex"
path = "examples/regex.rs"

[dev-dependencies]
atty = "0.2.14"
